
export const POPULAR_TAGS = [
  "Nickel Alloy",
  "Rental", 
  "Sour Gas",
  "Inspection",
  "Valve",
  "CRA",
  "Geothermal",
  "Subsea",
  "Storage",
  "Welding",
  "API Standard",
  "ASTM",
  "High Pressure",
  "Corrosion Resistant",
  "Stainless Steel",
  "Carbon Steel",
  "Duplex Steel",
  "Heat Transfer",
  "Pipeline",
  "Offshore",
  "Well Control",
  "Drilling",
  "PDC",
  "BOP",
  "Christmas Tree",
  "Flow Meter",
  "Measurement",
  "Digital",
  "Non-Invasive",
  "IP68",
  "TEMA",
  "Process Equipment"
]
